# Copyright (c) Facebook, Inc. and its affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
input_dim: "3, 160, 240"
_data:
  batch_size: 8
  map_eval_batch_size: 8
  modality: "image"

_modality:
  abs_pos_enc: True
  use_batch_norm_rel_net: True

opt: 
  lr: 1e-4